namespace FPL.Data.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class ModleBaseExctracted : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.Bonus", "PlayerInformationId", "dbo.PlayerInformations");
            DropForeignKey("dbo.CleanSheets", "PlayerInformationId", "dbo.PlayerInformations");
            DropForeignKey("dbo.GoalsScoreds", "PlayerInformationId", "dbo.PlayerInformations");
            DropForeignKey("dbo.Minutes", "PlayerInformationId", "dbo.PlayerInformations");
            DropForeignKey("dbo.ExplainFixtures", "PlayerInformationId", "dbo.PlayerInformations");
            DropForeignKey("dbo.Homes", "PlayerInformationId", "dbo.PlayerInformations");
            DropForeignKey("dbo.Assists", "PlayerInformationId", "dbo.PlayerInformations");
            DropForeignKey("dbo.Aways", "PlayerInformationId", "dbo.PlayerInformations");
            DropForeignKey("dbo.Bps", "PlayerInformationId", "dbo.PlayerInformations");
            DropForeignKey("dbo.OwnGoals", "PlayerInformationId", "dbo.PlayerInformations");
            DropForeignKey("dbo.PenaltiesMisseds", "PlayerInformationId", "dbo.PlayerInformations");
            DropForeignKey("dbo.PenaltiesSaveds", "PlayerInformationId", "dbo.PlayerInformations");
            DropForeignKey("dbo.Stats", "PlayerInformationId", "dbo.PlayerInformations");
            DropForeignKey("dbo.RedCards", "PlayerInformationId", "dbo.PlayerInformations");
            DropForeignKey("dbo.Saves", "PlayerInformationId", "dbo.PlayerInformations");
            DropForeignKey("dbo.YellowCards", "PlayerInformationId", "dbo.PlayerInformations");
            DropIndex("dbo.Bonus", new[] { "PlayerInformationId" });
            DropIndex("dbo.CleanSheets", new[] { "PlayerInformationId" });
            DropIndex("dbo.GoalsScoreds", new[] { "PlayerInformationId" });
            DropIndex("dbo.Minutes", new[] { "PlayerInformationId" });
            DropIndex("dbo.ExplainFixtures", new[] { "PlayerInformationId" });
            DropIndex("dbo.Stats", new[] { "PlayerInformationId" });
            DropIndex("dbo.Assists", new[] { "PlayerInformationId" });
            DropIndex("dbo.Homes", new[] { "PlayerInformationId" });
            DropIndex("dbo.Bps", new[] { "PlayerInformationId" });
            DropIndex("dbo.Aways", new[] { "PlayerInformationId" });
            DropIndex("dbo.OwnGoals", new[] { "PlayerInformationId" });
            DropIndex("dbo.PenaltiesMisseds", new[] { "PlayerInformationId" });
            DropIndex("dbo.PenaltiesSaveds", new[] { "PlayerInformationId" });
            DropIndex("dbo.RedCards", new[] { "PlayerInformationId" });
            DropIndex("dbo.Saves", new[] { "PlayerInformationId" });
            DropIndex("dbo.YellowCards", new[] { "PlayerInformationId" });
            AddColumn("dbo.HistoryPasts", "CreatedOn", c => c.DateTime(nullable: false));
            AddColumn("dbo.HistoryPasts", "IsDeleted", c => c.Boolean(nullable: false));
            AddColumn("dbo.Explains", "CreatedOn", c => c.DateTime(nullable: false));
            AddColumn("dbo.Explains", "IsDeleted", c => c.Boolean(nullable: false));
            AddColumn("dbo.ExplainDetails", "CreatedOn", c => c.DateTime(nullable: false));
            AddColumn("dbo.ExplainDetails", "IsDeleted", c => c.Boolean(nullable: false));
            AddColumn("dbo.Bonus", "CreatedOn", c => c.DateTime(nullable: false));
            AddColumn("dbo.Bonus", "IsDeleted", c => c.Boolean(nullable: false));
            AddColumn("dbo.CleanSheets", "CreatedOn", c => c.DateTime(nullable: false));
            AddColumn("dbo.CleanSheets", "IsDeleted", c => c.Boolean(nullable: false));
            AddColumn("dbo.GoalsScoreds", "CreatedOn", c => c.DateTime(nullable: false));
            AddColumn("dbo.GoalsScoreds", "IsDeleted", c => c.Boolean(nullable: false));
            AddColumn("dbo.Minutes", "CreatedOn", c => c.DateTime(nullable: false));
            AddColumn("dbo.Minutes", "IsDeleted", c => c.Boolean(nullable: false));
            AddColumn("dbo.ExplainFixtures", "CreatedOn", c => c.DateTime(nullable: false));
            AddColumn("dbo.ExplainFixtures", "IsDeleted", c => c.Boolean(nullable: false));
            AddColumn("dbo.Stats", "CreatedOn", c => c.DateTime(nullable: false));
            AddColumn("dbo.Stats", "IsDeleted", c => c.Boolean(nullable: false));
            AddColumn("dbo.Assists", "CreatedOn", c => c.DateTime(nullable: false));
            AddColumn("dbo.Assists", "IsDeleted", c => c.Boolean(nullable: false));
            AddColumn("dbo.Homes", "CreatedOn", c => c.DateTime(nullable: false));
            AddColumn("dbo.Homes", "IsDeleted", c => c.Boolean(nullable: false));
            AddColumn("dbo.Bps", "CreatedOn", c => c.DateTime(nullable: false));
            AddColumn("dbo.Bps", "IsDeleted", c => c.Boolean(nullable: false));
            AddColumn("dbo.Aways", "CreatedOn", c => c.DateTime(nullable: false));
            AddColumn("dbo.Aways", "IsDeleted", c => c.Boolean(nullable: false));
            AddColumn("dbo.OwnGoals", "CreatedOn", c => c.DateTime(nullable: false));
            AddColumn("dbo.OwnGoals", "IsDeleted", c => c.Boolean(nullable: false));
            AddColumn("dbo.PenaltiesMisseds", "CreatedOn", c => c.DateTime(nullable: false));
            AddColumn("dbo.PenaltiesMisseds", "IsDeleted", c => c.Boolean(nullable: false));
            AddColumn("dbo.PenaltiesSaveds", "CreatedOn", c => c.DateTime(nullable: false));
            AddColumn("dbo.PenaltiesSaveds", "IsDeleted", c => c.Boolean(nullable: false));
            AddColumn("dbo.RedCards", "CreatedOn", c => c.DateTime(nullable: false));
            AddColumn("dbo.RedCards", "IsDeleted", c => c.Boolean(nullable: false));
            AddColumn("dbo.Saves", "CreatedOn", c => c.DateTime(nullable: false));
            AddColumn("dbo.Saves", "IsDeleted", c => c.Boolean(nullable: false));
            AddColumn("dbo.YellowCards", "CreatedOn", c => c.DateTime(nullable: false));
            AddColumn("dbo.YellowCards", "IsDeleted", c => c.Boolean(nullable: false));
            AddColumn("dbo.Fixtures", "CreatedOn", c => c.DateTime(nullable: false));
            AddColumn("dbo.Fixtures", "IsDeleted", c => c.Boolean(nullable: false));
            AddColumn("dbo.FixturesSummaries", "CreatedOn", c => c.DateTime(nullable: false));
            AddColumn("dbo.FixturesSummaries", "IsDeleted", c => c.Boolean(nullable: false));
            AddColumn("dbo.Histories", "CreatedOn", c => c.DateTime(nullable: false));
            AddColumn("dbo.Histories", "IsDeleted", c => c.Boolean(nullable: false));
            AddColumn("dbo.HistorySummaries", "CreatedOn", c => c.DateTime(nullable: false));
            AddColumn("dbo.HistorySummaries", "IsDeleted", c => c.Boolean(nullable: false));
            CreateIndex("dbo.HistoryPasts", "IsDeleted");
            CreateIndex("dbo.Explains", "IsDeleted");
            CreateIndex("dbo.ExplainDetails", "IsDeleted");
            CreateIndex("dbo.Bonus", "IsDeleted");
            CreateIndex("dbo.CleanSheets", "IsDeleted");
            CreateIndex("dbo.GoalsScoreds", "IsDeleted");
            CreateIndex("dbo.Minutes", "IsDeleted");
            CreateIndex("dbo.ExplainFixtures", "IsDeleted");
            CreateIndex("dbo.Stats", "IsDeleted");
            CreateIndex("dbo.Assists", "IsDeleted");
            CreateIndex("dbo.Homes", "IsDeleted");
            CreateIndex("dbo.Bps", "IsDeleted");
            CreateIndex("dbo.Aways", "IsDeleted");
            CreateIndex("dbo.OwnGoals", "IsDeleted");
            CreateIndex("dbo.PenaltiesMisseds", "IsDeleted");
            CreateIndex("dbo.PenaltiesSaveds", "IsDeleted");
            CreateIndex("dbo.RedCards", "IsDeleted");
            CreateIndex("dbo.Saves", "IsDeleted");
            CreateIndex("dbo.YellowCards", "IsDeleted");
            CreateIndex("dbo.Fixtures", "IsDeleted");
            CreateIndex("dbo.FixturesSummaries", "IsDeleted");
            CreateIndex("dbo.Histories", "IsDeleted");
            CreateIndex("dbo.HistorySummaries", "IsDeleted");
            DropColumn("dbo.Bonus", "PlayerInformationId");
            DropColumn("dbo.CleanSheets", "PlayerInformationId");
            DropColumn("dbo.GoalsScoreds", "PlayerInformationId");
            DropColumn("dbo.Minutes", "PlayerInformationId");
            DropColumn("dbo.ExplainFixtures", "PlayerInformationId");
            DropColumn("dbo.Stats", "PlayerInformationId");
            DropColumn("dbo.Assists", "PlayerInformationId");
            DropColumn("dbo.Homes", "PlayerInformationId");
            DropColumn("dbo.Bps", "PlayerInformationId");
            DropColumn("dbo.Aways", "PlayerInformationId");
            DropColumn("dbo.OwnGoals", "PlayerInformationId");
            DropColumn("dbo.PenaltiesMisseds", "PlayerInformationId");
            DropColumn("dbo.PenaltiesSaveds", "PlayerInformationId");
            DropColumn("dbo.RedCards", "PlayerInformationId");
            DropColumn("dbo.Saves", "PlayerInformationId");
            DropColumn("dbo.YellowCards", "PlayerInformationId");
        }
        
        public override void Down()
        {
            AddColumn("dbo.YellowCards", "PlayerInformationId", c => c.Int(nullable: false));
            AddColumn("dbo.Saves", "PlayerInformationId", c => c.Int(nullable: false));
            AddColumn("dbo.RedCards", "PlayerInformationId", c => c.Int(nullable: false));
            AddColumn("dbo.PenaltiesSaveds", "PlayerInformationId", c => c.Int(nullable: false));
            AddColumn("dbo.PenaltiesMisseds", "PlayerInformationId", c => c.Int(nullable: false));
            AddColumn("dbo.OwnGoals", "PlayerInformationId", c => c.Int(nullable: false));
            AddColumn("dbo.Aways", "PlayerInformationId", c => c.Int(nullable: false));
            AddColumn("dbo.Bps", "PlayerInformationId", c => c.Int(nullable: false));
            AddColumn("dbo.Homes", "PlayerInformationId", c => c.Int(nullable: false));
            AddColumn("dbo.Assists", "PlayerInformationId", c => c.Int(nullable: false));
            AddColumn("dbo.Stats", "PlayerInformationId", c => c.Int(nullable: false));
            AddColumn("dbo.ExplainFixtures", "PlayerInformationId", c => c.Int(nullable: false));
            AddColumn("dbo.Minutes", "PlayerInformationId", c => c.Int(nullable: false));
            AddColumn("dbo.GoalsScoreds", "PlayerInformationId", c => c.Int(nullable: false));
            AddColumn("dbo.CleanSheets", "PlayerInformationId", c => c.Int(nullable: false));
            AddColumn("dbo.Bonus", "PlayerInformationId", c => c.Int(nullable: false));
            DropIndex("dbo.HistorySummaries", new[] { "IsDeleted" });
            DropIndex("dbo.Histories", new[] { "IsDeleted" });
            DropIndex("dbo.FixturesSummaries", new[] { "IsDeleted" });
            DropIndex("dbo.Fixtures", new[] { "IsDeleted" });
            DropIndex("dbo.YellowCards", new[] { "IsDeleted" });
            DropIndex("dbo.Saves", new[] { "IsDeleted" });
            DropIndex("dbo.RedCards", new[] { "IsDeleted" });
            DropIndex("dbo.PenaltiesSaveds", new[] { "IsDeleted" });
            DropIndex("dbo.PenaltiesMisseds", new[] { "IsDeleted" });
            DropIndex("dbo.OwnGoals", new[] { "IsDeleted" });
            DropIndex("dbo.Aways", new[] { "IsDeleted" });
            DropIndex("dbo.Bps", new[] { "IsDeleted" });
            DropIndex("dbo.Homes", new[] { "IsDeleted" });
            DropIndex("dbo.Assists", new[] { "IsDeleted" });
            DropIndex("dbo.Stats", new[] { "IsDeleted" });
            DropIndex("dbo.ExplainFixtures", new[] { "IsDeleted" });
            DropIndex("dbo.Minutes", new[] { "IsDeleted" });
            DropIndex("dbo.GoalsScoreds", new[] { "IsDeleted" });
            DropIndex("dbo.CleanSheets", new[] { "IsDeleted" });
            DropIndex("dbo.Bonus", new[] { "IsDeleted" });
            DropIndex("dbo.ExplainDetails", new[] { "IsDeleted" });
            DropIndex("dbo.Explains", new[] { "IsDeleted" });
            DropIndex("dbo.HistoryPasts", new[] { "IsDeleted" });
            DropColumn("dbo.HistorySummaries", "IsDeleted");
            DropColumn("dbo.HistorySummaries", "CreatedOn");
            DropColumn("dbo.Histories", "IsDeleted");
            DropColumn("dbo.Histories", "CreatedOn");
            DropColumn("dbo.FixturesSummaries", "IsDeleted");
            DropColumn("dbo.FixturesSummaries", "CreatedOn");
            DropColumn("dbo.Fixtures", "IsDeleted");
            DropColumn("dbo.Fixtures", "CreatedOn");
            DropColumn("dbo.YellowCards", "IsDeleted");
            DropColumn("dbo.YellowCards", "CreatedOn");
            DropColumn("dbo.Saves", "IsDeleted");
            DropColumn("dbo.Saves", "CreatedOn");
            DropColumn("dbo.RedCards", "IsDeleted");
            DropColumn("dbo.RedCards", "CreatedOn");
            DropColumn("dbo.PenaltiesSaveds", "IsDeleted");
            DropColumn("dbo.PenaltiesSaveds", "CreatedOn");
            DropColumn("dbo.PenaltiesMisseds", "IsDeleted");
            DropColumn("dbo.PenaltiesMisseds", "CreatedOn");
            DropColumn("dbo.OwnGoals", "IsDeleted");
            DropColumn("dbo.OwnGoals", "CreatedOn");
            DropColumn("dbo.Aways", "IsDeleted");
            DropColumn("dbo.Aways", "CreatedOn");
            DropColumn("dbo.Bps", "IsDeleted");
            DropColumn("dbo.Bps", "CreatedOn");
            DropColumn("dbo.Homes", "IsDeleted");
            DropColumn("dbo.Homes", "CreatedOn");
            DropColumn("dbo.Assists", "IsDeleted");
            DropColumn("dbo.Assists", "CreatedOn");
            DropColumn("dbo.Stats", "IsDeleted");
            DropColumn("dbo.Stats", "CreatedOn");
            DropColumn("dbo.ExplainFixtures", "IsDeleted");
            DropColumn("dbo.ExplainFixtures", "CreatedOn");
            DropColumn("dbo.Minutes", "IsDeleted");
            DropColumn("dbo.Minutes", "CreatedOn");
            DropColumn("dbo.GoalsScoreds", "IsDeleted");
            DropColumn("dbo.GoalsScoreds", "CreatedOn");
            DropColumn("dbo.CleanSheets", "IsDeleted");
            DropColumn("dbo.CleanSheets", "CreatedOn");
            DropColumn("dbo.Bonus", "IsDeleted");
            DropColumn("dbo.Bonus", "CreatedOn");
            DropColumn("dbo.ExplainDetails", "IsDeleted");
            DropColumn("dbo.ExplainDetails", "CreatedOn");
            DropColumn("dbo.Explains", "IsDeleted");
            DropColumn("dbo.Explains", "CreatedOn");
            DropColumn("dbo.HistoryPasts", "IsDeleted");
            DropColumn("dbo.HistoryPasts", "CreatedOn");
            CreateIndex("dbo.YellowCards", "PlayerInformationId");
            CreateIndex("dbo.Saves", "PlayerInformationId");
            CreateIndex("dbo.RedCards", "PlayerInformationId");
            CreateIndex("dbo.PenaltiesSaveds", "PlayerInformationId");
            CreateIndex("dbo.PenaltiesMisseds", "PlayerInformationId");
            CreateIndex("dbo.OwnGoals", "PlayerInformationId");
            CreateIndex("dbo.Aways", "PlayerInformationId");
            CreateIndex("dbo.Bps", "PlayerInformationId");
            CreateIndex("dbo.Homes", "PlayerInformationId");
            CreateIndex("dbo.Assists", "PlayerInformationId");
            CreateIndex("dbo.Stats", "PlayerInformationId");
            CreateIndex("dbo.ExplainFixtures", "PlayerInformationId");
            CreateIndex("dbo.Minutes", "PlayerInformationId");
            CreateIndex("dbo.GoalsScoreds", "PlayerInformationId");
            CreateIndex("dbo.CleanSheets", "PlayerInformationId");
            CreateIndex("dbo.Bonus", "PlayerInformationId");
            AddForeignKey("dbo.YellowCards", "PlayerInformationId", "dbo.PlayerInformations", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Saves", "PlayerInformationId", "dbo.PlayerInformations", "Id", cascadeDelete: true);
            AddForeignKey("dbo.RedCards", "PlayerInformationId", "dbo.PlayerInformations", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Stats", "PlayerInformationId", "dbo.PlayerInformations", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PenaltiesSaveds", "PlayerInformationId", "dbo.PlayerInformations", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PenaltiesMisseds", "PlayerInformationId", "dbo.PlayerInformations", "Id", cascadeDelete: true);
            AddForeignKey("dbo.OwnGoals", "PlayerInformationId", "dbo.PlayerInformations", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Bps", "PlayerInformationId", "dbo.PlayerInformations", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Aways", "PlayerInformationId", "dbo.PlayerInformations", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Assists", "PlayerInformationId", "dbo.PlayerInformations", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Homes", "PlayerInformationId", "dbo.PlayerInformations", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ExplainFixtures", "PlayerInformationId", "dbo.PlayerInformations", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Minutes", "PlayerInformationId", "dbo.PlayerInformations", "Id", cascadeDelete: true);
            AddForeignKey("dbo.GoalsScoreds", "PlayerInformationId", "dbo.PlayerInformations", "Id", cascadeDelete: true);
            AddForeignKey("dbo.CleanSheets", "PlayerInformationId", "dbo.PlayerInformations", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Bonus", "PlayerInformationId", "dbo.PlayerInformations", "Id", cascadeDelete: true);
        }
    }
}
